### ISSUE TITLE
Docs: Add README

### ISSUE THREAD

**Issue by JohJakob** [dervondenbergen/BaustelleLiveApp#1]
I want to know what this app is about and what it does! 😃

**Comment by dervondenbergen** [comment]
It will become an App to show the images from https://latest.baustelle.live but will add a README as soon as possible.

**Comment by dervondenbergen** [comment]
@JohJakob does the project make more sense now or is some information missing in your eyes?

**Comment by JohJakob** [comment]
Yes, perfect! Thanks for adding the README :)
